nom=input("entrez votre nom :")
print("bonjour" ,nom)
age=int(input("entrez votre année de naissance :"))
annee=int(input("entrez l'année en cours :"))
print("tu as")
w=annee-age
print(w)
print("ans")
print("dans 50 ans tu auras")
print(w+50)