texte1="A FORCE D'ALLER EN AVANT, IL PARVINT AU POINT OU LE BROUILLARD DE LA FUSILLADE DEVENAIT  TRANSPARENT. SI BIEN QUE LES TIRAILLEURS DE LA LIGNE RANGES ET A L'AFFUT DERRIERE LEUR LEVEE DE PAVES, ET LES TIRAILLEURS DE LA BANLIEUE MASSES A L'ANGLE DE LA RUE, SE MONTRERENT SOUDAINEMENT  QUELQUE CHOSE QUI REMUAIT DANS LA FUMEE. AU MOMENT OU GAVROCHE DEBARRASSAIT DE SES CARTOUCHES UN SERGENT GISANT PRES D'UNE BORNE, UNE BALLE FRAPPA LE CADAVRE."

texte2="IL LUI SUFFIT ALORS D'Y APPROFONDIR SON AGONISANT FRANGIN POUR VOIR S'ACCOMPLIR SON FORFAIT QUI, PAR SURCROIT, PROFITA AU PAYS, PUISQU'UN MOIS PLUS TARD, TOUT UN CHACUN S'ACCORDAIT POUR NANTIR L'INTRIGANT FLUX QUI SOURDAIT DU PUITS D'UN FORT POUVOIR CURATIF, SURTOUT ANTICATARRHAL, MAIS S'APPLIQUANT AUSSI A L'ALBUGO, A L'ANCHILOPS, AUX BUBONS, AUX CALCULS, AUX CHALAZIONS, AU TRISMUS, AU PITYRIASIS, AU MAL BLANC, AU PRURIGO, AU MAL CADUC, AU GLOSSANTHRAX."

texte3="JE RENTRE CHEZ MOI. SUR LE TROTTOIR, UN HOMME SE PROMENE, SES DEUX MUSETTES REMPLIES DE LEGUMES ENTRE SES DOIGTS. JE SUIS DERRIERE LUI ET BRUSQUEMENT IL SE RETOURNE ET ME HURLE BONJOUR ! IL ME VOIT, JE LE VOIS. UNE PETITE SECONDE JE CROIS QUE C'EST LE PERE D'UNE COPINE. OR, COMME IL M'EST INCONNU, JE LE CONTOURNE. JE CONTINUE MON CHEMIN JUSQUE CHEZ MOI."

texte4="AZERTYUIOPQSDFGHJKLMWXCVBN"
lettre={}
alphabet=('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
for i in texte4:
    for caractere in alphabet:
    
        if i==caractere and caractere not in lettre:
            lettre[caractere]=1
        elif i==caractere and caractere in lettre:
            lettre[caractere]+=1
print(lettre)
print("Le texte contient ",lettre['A']," fois la lettre A et ",lettre['E']," fois la lettre E")